version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    container_name: mileage-mysql
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=mileage
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user1234
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci