# database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mileage?characterEncoding=utf8
    username: user
    password: user1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

logging:
  level:
    com.example.mileage: debug
    org.hibernate.type.descriptor.sql: trace
